# Generated by Django 6.0.3 on 2026-05-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportinventory',
            name='abc_class',
        ),
        migrations.RemoveField(
            model_name='reportinventory',
            name='product_ved_class',
        ),
        migrations.RemoveField(
            model_name='reportsales',
            name='product_ved_class',
        ),
    ]
