# Generated by Django 5.2.15 on 2026-06-11 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_remove_reportinventory_abc_class_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportpurchases",
            name="product_category",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="reportsales",
            name="payment_method",
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="reportsalesreturns",
            name="product_category",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name="reportfinancial",
            index=models.Index(
                fields=["entry_date", "location_id"],
                name="report_fina_entry_d_915ea2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportpurchases",
            index=models.Index(
                fields=["bill_date", "location_id"],
                name="report_purc_bill_da_a65f65_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportsales",
            index=models.Index(
                fields=["sale_date", "location_id"],
                name="report_sale_sale_da_ce5c7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportsalesreturns",
            index=models.Index(
                fields=["return_date", "location_id"],
                name="report_sale_return__565a25_idx",
            ),
        ),
    ]
