# Generated by Django 5.2.12 on 2026-05-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dashboardpref'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('user_label', models.CharField(blank=True, max_length=120)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('body_summary', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['timestamp', 'path'], name='audit_log_timesta_2f8785_idx'), models.Index(fields=['user_id', 'timestamp'], name='audit_log_user_id_835db7_idx')],
            },
        ),
    ]
