# Generated by Django 5.2.12 on 2026-06-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportinventory',
            name='gmroi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='reportinventory',
            name='inventory_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
