# Generated by Django 5.2.12 on 2026-06-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_reportinventory_gmroi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportfinancial',
            name='account_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reportfinancial',
            name='account_subtype',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reportfinancial',
            name='parent_account_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reportfinancial',
            name='party_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
