# Generated by Django 5.2.12 on 2026-06-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_dedupe_report_source_rows'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reportfinancial',
            constraint=models.UniqueConstraint(fields=('source_entry_id', 'source_line_id'), name='uniq_report_financial_source_line'),
        ),
        migrations.AddConstraint(
            model_name='reportgst',
            constraint=models.UniqueConstraint(fields=('source_table', 'source_id'), name='uniq_report_gst_source'),
        ),
        migrations.AddConstraint(
            model_name='reportpurchases',
            constraint=models.UniqueConstraint(fields=('is_return', 'source_id', 'source_line_id'), name='uniq_report_purchases_source_line'),
        ),
        migrations.AddConstraint(
            model_name='reportsales',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id', 'source_line_id'), name='uniq_report_sales_source_line'),
        ),
        migrations.AddConstraint(
            model_name='reportsalesreturns',
            constraint=models.UniqueConstraint(fields=('source_id', 'source_line_id'), name='uniq_report_sales_returns_source_line'),
        ),
    ]
