# Generated by Django 5.2.12 on 2026-06-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_reportfinancial_uniq_report_financial_source_line_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reportfinancial',
            index=models.Index(fields=['location_id', 'entry_date'], name='rep_fin_loc_entrydate'),
        ),
        migrations.AddIndex(
            model_name='reportpurchases',
            index=models.Index(fields=['is_return', 'bill_date'], name='rep_purch_isret_bdate'),
        ),
        migrations.AddIndex(
            model_name='reportsales',
            index=models.Index(fields=['location_id', 'sale_date'], name='rep_sales_loc_saledate'),
        ),
    ]
