# Generated by Django 6.0.3 on 2026-04-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_type', models.CharField(db_index=True, max_length=30)),
                ('source_id', models.IntegerField()),
                ('error_message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pipeline_error',
            },
        ),
        migrations.CreateModel(
            name='PipelineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_type', models.CharField(db_index=True, max_length=30)),
                ('last_synced_id', models.IntegerField(default=0)),
                ('last_run_at', models.DateTimeField(auto_now=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'pipeline_log',
            },
        ),
    ]
