"""Performance baseline + benchmark harness — DASH-E20-F01-US03.

Hits every dashboard endpoint via Django's test client (no network /
gunicorn variance) N times, captures view_ms and SQL counts, computes
p50/p95, and writes a markdown report at docs/PERF_BASELINE.md.

The DASH-E00-A03 NFR sets a p95 budget of 800 ms per endpoint. This
script flags any endpoint that exceeds it, so the baseline is also a
gate.

Run from the repo root:
    DJANGO_SETTINGS_MODULE=dashboard_project.settings python3 scripts/perf_baseline.py

Or against a populated DB by setting DJANGO_DB_PATH:
    DJANGO_DB_PATH=/path/to/db.sqlite3 python3 scripts/perf_baseline.py
"""
from __future__ import annotations

import json
import os
import statistics
import sys
import time
from pathlib import Path
from typing import Dict, List

REPO_ROOT = Path(__file__).resolve().parents[1]
DOCS_DIR = REPO_ROOT / "docs"
DOCS_DIR.mkdir(exist_ok=True)

# Bootstrap Django in-process so we can use the test client without a
# running gunicorn.
sys.path.insert(0, str(REPO_ROOT / "backend"))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "dashboard_project.settings")

import django  # noqa: E402

django.setup()

from django.test import Client  # noqa: E402
from django.db import connection, reset_queries  # noqa: E402
from django.conf import settings  # noqa: E402

# Force connection.queries to be captured (only happens in DEBUG).
settings.DEBUG = True

# Endpoints worth measuring. Lifted from the smoke-test list so the two
# stay in sync.
ENDPOINTS = [
    "/api/executive/kpis/",
    "/api/executive/revenue-trend/",
    "/api/executive/channel-mix/",
    "/api/executive/category-revenue/",
    "/api/executive/top-products/",
    "/api/executive/inventory-alerts/",
    "/api/executive/pending-actions/",
    "/api/executive/today-sales/",
    "/api/executive/filter-options/",
    "/api/sales/overview/",
    "/api/sales/payment-mix/",
    "/api/sales/products/",
    "/api/financial/pnl/",
    "/api/financial/balance-sheet/",
    "/api/financial/cash-flow/",
    "/api/inventory/overview/",
    "/api/inventory/by-category/",
    "/api/inventory/expiry/",
    "/api/procurement/overview/",
    "/api/procurement/supplier-scorecard/",
    "/api/gst/overview/",
    "/api/tds/overview/",
    "/api/working-capital/overview/",
    "/api/location/comparison/",
    "/api/product/overview/",
    "/api/dispatch/pipeline/",
    "/api/loyalty/overview/",
    "/api/audit/overview/",
    "/api/pipeline/history/",
    "/api/health/",
    "/api/health/data/",
    "/api/reconcile/sales/",
    "/api/reconcile/gst/",
    "/api/reconcile/cash/",
    "/api/reconcile/summary/",
    "/api/prefs/",
]

# DASH-E00-A03 budgets
P95_BUDGET_MS = 800.0
P50_BUDGET_MS = 400.0


def measure(client: Client, path: str, runs: int) -> Dict:
    times: List[float] = []
    sql_counts: List[int] = []
    statuses: List[int] = []
    for _ in range(runs):
        reset_queries()
        t0 = time.perf_counter()
        resp = client.get(path)
        dt_ms = (time.perf_counter() - t0) * 1000.0
        times.append(dt_ms)
        sql_counts.append(len(connection.queries))
        statuses.append(resp.status_code)

    times.sort()
    return {
        "path": path,
        "runs": runs,
        "status_modes": list(sorted(set(statuses))),
        "p50_ms": round(statistics.median(times), 1),
        "p95_ms": round(times[max(0, int(len(times) * 0.95) - 1)], 1),
        "max_ms": round(max(times), 1),
        "mean_sql": round(statistics.mean(sql_counts), 1),
        "max_sql": max(sql_counts),
    }


def main() -> int:
    runs = int(os.environ.get("PERF_RUNS", "10"))
    client = Client()

    # Warm up the connection so the first request isn't penalised for
    # SQLite open + Django app boot.
    for path in ENDPOINTS[:3]:
        client.get(path)

    results = []
    failed = []
    for path in ENDPOINTS:
        try:
            r = measure(client, path, runs)
        except Exception as exc:
            failed.append({"path": path, "error": str(exc)})
            continue
        results.append(r)

    # Sort slowest first so attention naturally lands on the worst rows.
    results.sort(key=lambda r: r["p95_ms"], reverse=True)

    over_budget = [r for r in results if r["p95_ms"] > P95_BUDGET_MS]

    md_lines: List[str] = []
    md_lines.append("# Performance Baseline — healthcare-dashboard")
    md_lines.append("")
    md_lines.append(
        f"Generated by `scripts/perf_baseline.py` over {runs} runs per endpoint, "
        "single-process Django test client. SQL counts captured via "
        "`connection.queries` with DEBUG forced on for the run."
    )
    md_lines.append("")
    md_lines.append(
        f"**Budget (DASH-E00-A03):** p95 ≤ {P95_BUDGET_MS:.0f} ms · p50 ≤ "
        f"{P50_BUDGET_MS:.0f} ms."
    )
    md_lines.append("")
    md_lines.append(
        f"**Endpoints over p95 budget:** {len(over_budget)} of {len(results)}"
    )
    md_lines.append("")

    md_lines.append("| Endpoint | p50 ms | p95 ms | max ms | mean SQL | max SQL | status |")
    md_lines.append("|---|---:|---:|---:|---:|---:|---|")
    for r in results:
        flag = "🔴" if r["p95_ms"] > P95_BUDGET_MS else ("🟡" if r["p95_ms"] > P50_BUDGET_MS else "🟢")
        md_lines.append(
            f"| `{r['path']}` | {r['p50_ms']} | {r['p95_ms']} | {r['max_ms']} | "
            f"{r['mean_sql']} | {r['max_sql']} | {flag} {','.join(map(str, r['status_modes']))} |"
        )

    if failed:
        md_lines.append("")
        md_lines.append("## Failed endpoints")
        md_lines.append("")
        for f in failed:
            md_lines.append(f"- `{f['path']}` — {f['error']}")

    md_lines.append("")
    md_lines.append("## How to read")
    md_lines.append("")
    md_lines.append(
        "🟢 = within p50 budget · 🟡 = within p95 but above p50 · 🔴 = over p95 (release-blocker per the NFR). "
        "A high `mean SQL` count usually means a missing aggregation or N+1 — the report queryset is per-row instead of `.values().annotate(Sum())`."
    )

    out = DOCS_DIR / "PERF_BASELINE.md"
    out.write_text("\n".join(md_lines))
    print(f"Wrote {out} — {len(results)} endpoints measured, {len(over_budget)} over budget.")

    # Also dump JSON for downstream tooling.
    (DOCS_DIR / "PERF_BASELINE.json").write_text(
        json.dumps({"runs": runs, "budget": {"p50_ms": P50_BUDGET_MS, "p95_ms": P95_BUDGET_MS}, "results": results, "failed": failed}, indent=2)
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
